services:
    cosmos-backend:
        image: ghcr.io/cosmos-capstone/backend:1730018998
        ports:
            - 8000:8000
        volumes:
            - ./db.sqlite3:/app/db.sqlite3
        restart: always
