services:
    cosmos-backend:
        image: ghcr.io/cosmos-capstone/backend:latest
        ports:
            - 8000:8000
        environment:
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_DEBUG_MODE=${DJANGO_DEBUG_MODE}
        volumes:
            - ./db.sqlite3:/app/db.sqlite3
        restart: always
