# Generated by Django 4.2.3 on 2024-11-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('asset_category', models.CharField(choices=[('korean_stock', 'Korean Stock'), ('american_stock', 'American Stock'), ('korean_bond', 'Korean Bond'), ('american_bond', 'American Bond'), ('fund', 'Fund'), ('commodity', 'Commodity'), ('gold', 'Gold'), ('deposit', 'Deposit'), ('savings', 'Savings Account'), ('cash', 'Cash')], max_length=50)),
                ('asset_symbol', models.CharField(max_length=20)),
                ('asset_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
