# Generated by Django 5.1.2 on 2024-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('asset_category', models.CharField(choices=[('korean_stock', 'Korean Stock'), ('american_stock', 'American Stock'), ('korean_bond', 'Korean Bond'), ('american_bond', 'American Bond'), ('commodity', 'Commodity'), ('gold', 'Gold'), ('deposit', 'Deposit')], max_length=50)),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=50)),
                ('bond_name', models.CharField(max_length=50)),
                ('fund_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
