# Generated by Django 5.1.1 on 2024-10-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_amount_transaction_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_category',
            field=models.CharField(blank=True, choices=[('korean_stock', 'Korean Stock'), ('american_stock', 'American Stock'), ('korean_bond', 'Korean Bond'), ('american_bond', 'American Bond'), ('commodity', 'Commodity'), ('gold', 'Gold'), ('deposit', 'Deposit')], max_length=50, null=True),
        ),
    ]
